// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbJpl9nB4HOatxIq-XEeqOuFkHv-Wkb9I',
    appId: '1:468329215327:web:e47c7a5d42622fc3b372ea',
    messagingSenderId: '468329215327',
    projectId: 'my-first-app-ac4e9',
    authDomain: 'my-first-app-ac4e9.firebaseapp.com',
    storageBucket: 'my-first-app-ac4e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGaAA8jt-1EG4NpRJCHEQ04rok8A7prSs',
    appId: '1:468329215327:android:9cdf00a5c42408bcb372ea',
    messagingSenderId: '468329215327',
    projectId: 'my-first-app-ac4e9',
    storageBucket: 'my-first-app-ac4e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkdXw3WelYbTHj47ibAFYBHs6cfPAb3xU',
    appId: '1:468329215327:ios:5747be49fd7e8002b372ea',
    messagingSenderId: '468329215327',
    projectId: 'my-first-app-ac4e9',
    storageBucket: 'my-first-app-ac4e9.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkdXw3WelYbTHj47ibAFYBHs6cfPAb3xU',
    appId: '1:468329215327:ios:5747be49fd7e8002b372ea',
    messagingSenderId: '468329215327',
    projectId: 'my-first-app-ac4e9',
    storageBucket: 'my-first-app-ac4e9.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbJpl9nB4HOatxIq-XEeqOuFkHv-Wkb9I',
    appId: '1:468329215327:web:4d24ec2b725a4d57b372ea',
    messagingSenderId: '468329215327',
    projectId: 'my-first-app-ac4e9',
    authDomain: 'my-first-app-ac4e9.firebaseapp.com',
    storageBucket: 'my-first-app-ac4e9.firebasestorage.app',
  );
}
